<a href="https://colab.research.google.com/github/iamharkirat/EDA/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Introduction to Tensor

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [6]:
# create constant
scaler=tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
# check dimensions of scaler
scaler.ndim

0

In [8]:
# create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
# create matrix (has more than 1 dimension)
matrix=tf.constant([[10,7],
                    [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [12]:
# another matrix
another_matrix=tf.constant([[10. , 7,],
                            [3. , 2.],
                            [8. , 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
another_matrix.ndim

2